// Please do not change these values. If you change these values, sitemap will generate wrong pages.
export const pages = [
  "about-us",
  "best-dedicated-hosting",
  "best-reseller-hosting",
  "best-shared-hosting",
  "best-vps-hosting",
  "best-woocommerce-hosting",
  "best-wordpress-hosting",
  "best-wordpress-plugins",
  "best-wordpress-themes",
  "blog",
  "contact-us",
  "coupons-and-promo",
  "drupal-theme-detector",
  "joomla-theme-detector",
  "magento-theme-detector",
  "moodle-theme-detector",
  "prestashop-theme-detector",
  "shopify-theme-detector",
  "top-ten-hosting",
];
